#!/usr/bin/env python3
"""CLI entry point for code-index analysis.

Runs analyzers against parsed source declarations and generates a
structured findings report in markdown.

Usage:
    python analyze.py --config aidocs.yaml
    python analyze.py --config aidocs.yaml --analyzer structural_health
    python analyze.py --config aidocs.yaml --out custom-report.md
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

from analyzers.base import Analyzer, Finding
from analyzers.structural_health import StructuralHealthAnalyzer
from pipeline import ModuleData, load_module

SEVERITY_ICON = {"error": "E", "warning": "W", "info": "I"}
SEVERITY_ORDER = {"error": 0, "warning": 1, "info": 2}

AVAILABLE_ANALYZERS: dict[str, type[Analyzer]] = {
    "structural_health": StructuralHealthAnalyzer,
}


def load_modules_from_config(config_path: Path) -> tuple[list[ModuleData], dict]:
    """Load and parse all modules from config file.

    Returns (modules, raw_config).
    """
    project_root = config_path.resolve().parent
    config = yaml.safe_load(config_path.read_text(encoding="utf-8"))
    language = config.get("language", "kotlin")
    merge_threshold = config.get("merge_threshold", 2)

    modules = []
    for mod in config.get("modules", []):
        source_dirs = [project_root / d for d in mod["source_dirs"]]
        data = load_module(
            name=mod["name"],
            source_dirs=source_dirs,
            prefix=mod["prefix"],
            language=language,
            merge_threshold=merge_threshold,
        )
        if data:
            modules.append(data)

    return modules, config


def build_analyzer(name: str, config: dict) -> Analyzer:
    """Instantiate an analyzer by name with optional config overrides."""
    cls = AVAILABLE_ANALYZERS.get(name)
    if cls is None:
        raise ValueError(f"Unknown analyzer: {name}. Available: {', '.join(AVAILABLE_ANALYZERS)}")
    analysis_cfg = config.get("analysis", {}) or {}
    analyzer_cfg = analysis_cfg.get(name, {}) or {}
    return cls(analyzer_cfg)


def generate_report(findings: list[Finding], analyzer_names: list[str]) -> str:
    """Generate markdown report from findings."""
    lines = [
        "# Code Analysis Report",
        "",
        "> Auto-generated by [code-index analyzers](../tools/code-index/). Do not edit manually.",
        "",
    ]

    if not findings:
        lines.append("No findings.")
        return "\n".join(lines)

    # Summary counts
    error_count = sum(1 for f in findings if f.severity == "error")
    warning_count = sum(1 for f in findings if f.severity == "warning")
    info_count = sum(1 for f in findings if f.severity == "info")

    lines.append("## Summary")
    lines.append("")
    lines.append(f"| Severity | Count |")
    lines.append(f"|----------|-------|")
    lines.append(f"| Errors   | {error_count} |")
    lines.append(f"| Warnings | {warning_count} |")
    lines.append(f"| Info     | {info_count} |")
    lines.append(f"| **Total**| **{len(findings)}** |")
    lines.append("")

    # Group by category
    categories: dict[str, list[Finding]] = {}
    for f in findings:
        categories.setdefault(f.category, []).append(f)

    # Sort categories: errors first, then warnings, then info
    def category_severity(cat: str) -> int:
        items = categories[cat]
        return min(SEVERITY_ORDER.get(f.severity, 9) for f in items)

    for category in sorted(categories, key=category_severity):
        items = categories[category]
        items.sort(key=lambda f: (SEVERITY_ORDER.get(f.severity, 9), f.package, f.declaration))

        title = category.replace("-", " ").title()
        lines.append(f"## {title}")
        lines.append("")
        lines.append("| Sev | Declaration | Package | Message |")
        lines.append("|-----|-------------|---------|---------|")
        for f in items:
            icon = SEVERITY_ICON.get(f.severity, "?")
            lines.append(f"| {icon} | {f.declaration} | {f.package} | {f.message} |")
        lines.append("")

    # Analyzers used
    lines.append("---")
    lines.append("")
    lines.append(f"*Analyzers: {', '.join(analyzer_names)}*")
    lines.append("")

    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description="Run code-index analyzers")
    parser.add_argument("--config", type=Path, required=True, help="Path to aidocs.yaml")
    parser.add_argument("--analyzer", type=str, help="Run only this analyzer (default: all)")
    parser.add_argument("--out", type=Path, help="Output file (default: <output_dir>/analysis.md)")

    args = parser.parse_args()

    # Load modules
    print("Loading modules...")
    modules, config = load_modules_from_config(args.config)
    if not modules:
        print("No modules found.", file=sys.stderr)
        sys.exit(1)

    # Determine which analyzers to run
    if args.analyzer:
        analyzer_names = [args.analyzer]
    else:
        analyzer_names = list(AVAILABLE_ANALYZERS.keys())

    # Run analyzers
    all_findings: list[Finding] = []
    for name in analyzer_names:
        print(f"Running analyzer: {name}")
        analyzer = build_analyzer(name, config)
        findings = analyzer.analyze(modules)
        all_findings.extend(findings)
        print(f"  {len(findings)} findings")

    # Generate report
    report = generate_report(all_findings, analyzer_names)

    # Determine output path
    project_root = args.config.resolve().parent
    output_dir = project_root / config.get("output_dir", "docs/code-index")
    output_path = args.out or (output_dir / "analysis.md")
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(report, encoding="utf-8")

    print(f"\nAnalysis report: {output_path}")
    print(f"  {len(all_findings)} total findings")


if __name__ == "__main__":
    main()
